# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: git checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: NPM RUN
      run: npm run start
      env:
        GIT_URL: ${{ env.GIT_URL }}
        MAIL_ENABLED: ${{ env.MAIL_ENABLED }}
        SMTP_SERVER: ${{ env.SMTP_SERVER }}
        SMTP_PORT: ${{ env.SMTP_PORT }}
        SMTP_TLS: ${{ env.SMTP_TLS }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        RECEIVER: ${{ env.RECEIVER }}
        SLACK_ENABLED: ${{ env.SLACK_ENABLED }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
